plugins:
  - babel
  - import
  - jest

env:
  node: true
  jest: true
  browser: true
  es6: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 11
  sourceType: module

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0
